target = open("output.txt", "a")
target.write("here is some more text")
target.write("\n")
target.write("You can put in as many writes as you need.\n")
target.close()
target.write("You can put in as many writes as you need.\n")
